[book]
authors = ["DeltaChat Contributors"]
language = "en"
src = "./"
title = "Webxdc"

[output.html]
default-theme = "Rust"
additional-css = ["custom.css"]
git-repository-url = "https://github.com/webxdc/website/tree/main/src-docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/webxdc/website/edit/main/src-docs/{path}"

[output.html.redirect]
"/spec.html" = "/spec/index.html"
"/tips_and_tricks.html" = "/tips_and_tricks/index.html"
"/intro.html" = "/get_started.html"

[output.linkcheck]
